import { Pipeline, EsiContext } from "../core/Pipeline";
import { QueueManager } from "../core/QueueManager";
import { HttpClient } from "../core/HttpClient";
import { createRateLimitMiddleware } from "../middlewares/rate-limit";
import { EsiScope, GeneratedApi } from "../api/GeneratedApi";
import { EsiRequester } from "./EsiRequester";
import { TokenProvider } from "../auth/TokenProvider";
import { createAuthMiddleware } from "../middlewares/auth";
import { EsiApiError } from "../core/errors";
import { AuthClient } from "./AuthClient";
import { camelToSnakeObj, snakeToCamelObj } from "../utils/transformer";
import {
    PublicCharacter,
    PublicAlliance,
    PublicCorporation,
    PublicContract,
} from "../domains";
import { Region } from "../domains/Region";

/**
 * Configuration object for the HTTP User-Agent header.
 *
 * @remarks
 * CCP Games strictly requires all third-party applications to identify themselves
 * when making requests to the ESI API. Failure to provide accurate contact information
 * may result in your application being permanently blocked. See
 * https://developers.eveonline.com/docs/services/esi/best-practices/#user-agents
 * for further details.
 */
export interface UserAgentConfig {
    /**
     * The name of your application, service, or tool.
     * @example "MyEveFleetTracker"
     */
    appName: string;

    /**
     * A direct way of CCP Games to contact you if there is an issue with your traffic.
     * This is usually an email address or a Discord username.
     * @example "admin@example.com"
     * @example "discord:user123"
     */
    contact: string;

    /**
     * A URL pointing to the public source code repository of your application.
     * Providing this is optional but highly recommended by CCP Games.
     */
    repository?: string;
}

/**
 * Configuration options required to instantiate the EsiClient.
 */
export interface EsiClientOptions {
    /**
     * The User-Agent identification for your applications.
     * You can provide a structured `UserAgentConfig` object or a raw string.
     * If a string is provided, it must clearly identify your app and contact info.
     */
    agent: UserAgentConfig | string;

    /**
     * The Client ID obtained from the EVE Online Developers portal.
     * This is used for OAuth2 authentication flows.
     */
    clientId?: string;

    /**
     * The maximum amount of time, in milliseconds, to wait for an HTTP response
     * before aborting the request.
     * @default 10000 (10 seconds)
     */
    timeoutMs?: number;

    /**
     * An instance of a TokenProvider.
     * This provider is responsible for supplying valid OAuth2 access tokens
     * when the client requests an authenticated endpoint.
     */
    tokenProvider?: TokenProvider;
}

/**
 * Defines the permitted data types for URL query string parameters.
 */
type QueryParamValue =
    | string
    | number
    | boolean
    | string[]
    | number[]
    | string[][]
    | number[][]
    | undefined
    | null;

/**
 * The internal configuration object used to execute a single HTTP request.
 * @remarks
 * This object is typically generated by the automated API wrapper methods
 * and passed down into the EsiClient pipeline. It contains all the necessary
 * routing, payload and security requirements for a specific ESI endpoint.
 */
export interface RequestOptions {
    method: "GET" | "POST" | "PUT" | "DELETE";
    path: string;
    query?: Record<string, QueryParamValue>;
    headers?: Record<string, string>;
    body?: unknown;
    rateLimitGroup?: string;
    requiresAuth: boolean;
    scopes?: EsiScope[];
}

/**
 * The core client and execution engine for the library.
 *
 * @remarks
 * This class serves as the central hub for all interactions with the EVE Online ESI API.
 * It manages the HTTP request pipeline, automated data transformations, rate limiting
 * queues and authentication middleware. It also provides domain-specific factory methods
 * for accessing higher-level abstractions like characters, alliances.
 */
export class EsiClient implements EsiRequester {
    private readonly pipeline: Pipeline;
    private readonly queueManager: QueueManager;
    private readonly httpClient: HttpClient;
    private readonly LIBRARY_AGENT = "@strata/esi/0.1.0";

    /**
     * The auto-generated API surface containing all ESI endpoints.
     */
    public readonly api: GeneratedApi;
    private readonly formattedUserAgent: string;

    /**
     * @param options - The configuration options required to set up the client.
     */
    constructor(private readonly options: EsiClientOptions) {
        this.formattedUserAgent = this.buildUserAgent(options.agent);

        this.pipeline = new Pipeline();
        this.queueManager = new QueueManager();
        this.httpClient = new HttpClient({
            timeoutMs: options.timeoutMs || 10_000,
        });

        this.pipeline.use(createAuthMiddleware(options.tokenProvider));
        this.pipeline.use(createRateLimitMiddleware(this.queueManager));

        this.pipeline.use(async (ctx, next) => {
            ctx.request.headers.set("User-Agent", this.formattedUserAgent);
            await this.httpClient.request(ctx);
            await next();
        });

        this.api = new GeneratedApi(this);
    }

    /**
     * Constructs a compliant User-Agent string based on the provided configuration.
     *
     * @param agent - The user-defined string or configuration object.
     * @returns A properly formatted User-Agent string appending the library version.
     */
    private buildUserAgent(agent: UserAgentConfig | string): string {
        if (typeof agent === "string") {
            return `${agent.trim()} ${this.LIBRARY_AGENT}`;
        }

        const { appName, contact, repository } = agent;
        const repoString = repository ? `; +${repository}` : "";

        return `${appName} (${contact}${repoString}) ${this.LIBRARY_AGENT}`;
    }

    /**
     * Executes an HTTP request against the ESI API through the internal pipeline.
     *
     * @remarks
     * This method automatically handles the transformation of request payloads and query parameters
     * from camelCase to snake_case before transmission. Upon receiving a response, it converts
     * the snake_case payload back to camelCase before returning it to the caller.
     *
     * @typeParam T - The expected return type of the response data.
     * @param options - The routing, payload, and configuration details for this specific request.
     * @param userId - An optional internal identifier representing the authenticated user executing the request.
     * @returns A promise that resolves to the strongly-typed, camelCase formatted response data.
     * @throws {EsiApiError} Thrown when the HTTP response status code is 400 or greater.
     */
    public async request<T>(
        options: RequestOptions,
        userId?: number,
    ): Promise<T> {
        let route = options.path;

        const safeQuery = options.query
            ? camelToSnakeObj(options.query)
            : undefined;

        if (safeQuery) {
            const searchParams = new URLSearchParams();
            for (const [key, value] of Object.entries(safeQuery)) {
                if (value !== undefined && value !== null) {
                    searchParams.append(key, String(value));
                }
            }
            const qs = searchParams.toString();
            if (qs) route += `?${qs}`;
        }

        const headers = new Headers();
        headers.set("Content-Type", "application/json");
        if (options.headers) {
            for (const [key, value] of Object.entries(options.headers)) {
                headers.set(key, String(value));
            }
        }

        const safeBody = options.body
            ? camelToSnakeObj(options.body)
            : undefined;

        const ctx: EsiContext = {
            request: {
                method: options.method,
                route,
                headers,
                body: safeBody,
            },
            state: {
                rateLimitGroup: options.rateLimitGroup || "default",
                userId,
                isAuthRequired: options.requiresAuth,
            },
        };

        const result = await this.pipeline.execute(ctx);

        if (result.response && result.response.status >= 400) {
            throw new EsiApiError(
                result.response.status,
                result.response.data,
                `ESI request failed on ${options.method} ${options.path}`,
            );
        }

        return snakeToCamelObj(result.response?.data) as T;
    }

    /**
     * Creates a scoped client instance dedicated to a specific authenticated user.
     *
     * @remarks
     * This method allows developers to execute authenticated requests on behalf of a specific
     * character without needing to pass the user ID into every individual method call.
     *
     * @param userId - The internal identifier of the authenticated user.
     * @returns An `AuthClient` instance pre-configured with the provided user ID.
     */
    public as(userId: number): AuthClient {
        const scopedRequester: EsiRequester = {
            request: <T>(options: RequestOptions) => {
                return this.request<T>(options, userId);
            },
        };

        const scopedApi = new GeneratedApi(scopedRequester);

        return new AuthClient(scopedApi, userId);
    }

    /**
     * Retrieves a domain wrapper for public character operations.
     *
     * @param id - The EVE Online character ID.
     * @returns A `PublicCharacter` instance providing abstract methods for this entity.
     */
    public character(id: number) {
        return new PublicCharacter(this.api, id);
    }

    /**
     * Retrieves a domain wrapper for public alliance operations.
     *
     * @param id - The EVE Online alliance ID.
     * @returns A `PublicAlliance` instance providing abstract methods for this entity.
     */
    public alliance(id: number) {
        return new PublicAlliance(this.api, id);
    }

    /**
     * Fetches all active alliance IDs and wraps them in domain objects.
     *
     * @returns A promise that resolves to an array of `PublicAlliance` instances.
     */
    public get alliances() {
        return {
            list: () => this.api.getAlliances(),
        };
    }

    /**
     * Retrieves a domain wrapper for public corporation operations.
     *
     * @param id - The EVE Online corporation ID.
     * @returns A `PublicCorporation` instance providing abstract methods for this entity.
     */
    public corporation(id: number) {
        return new PublicCorporation(this.api, id);
    }

    public get corporations() {
        return {
            npcs: () => this.api.getCorporationsNpccorps(),
        };
    }

    /**
     * Retrieves a domain wrapper for contract operations.
     *
     * @param id - The EVE Online contract ID.
     */
    public contract(id: number) {
        return new PublicContract(this.api, id);
    }

    /**
     * Retrieves paginated list of all public contracts in the given region
     */
    public region(regionId: number) {
        return new Region(this.api, regionId);
    }

    public get dogma() {
        return {
            attributes: {
                list: () => this.api.getDogmaAttributes(),
            },
            attribute: (id: number) => ({
                fetch: () => this.api.getDogmaAttributesAttributeId(id),
            }),
            effects: {
                list: () => this.api.getDogmaEffects(),
            },
            effect: (id: number) => ({
                fetch: () => this.api.getDogmaEffectsEffectId(id),
            }),
            dynamicItem: (typeId: number, itemId: number) => ({
                fetch: () =>
                    this.api.getDogmaDynamicItemsTypeIdItemId(itemId, typeId),
            }),
        };
    }

    public get fw() {
        return {
            leaderboads: {
                characters: () => this.api.getFwLeaderboardsCharacters(),
                corporations: () => this.api.getFwLeaderboardsCorporations(),
            },
            stats: () => this.api.getFwStats(),
            systems: () => this.api.getFwSystems(),
            wars: () => this.api.getFwWars(),
        };
    }

    public async incursions() {
        return this.api.getIncursions();
    }

    public get industry() {
        return {
            facilities: () => this.api.getIndustryFacilities(),
            systems: () => this.api.getIndustrySystems(),
        };
    }

    public get insurance() {
        return {
            prices: () => this.api.getInsurancePrices(),
        };
    }

    public killmail(id: number, hash: string) {
        return {
            fetch: () => this.api.getKillmailsKillmailIdKillmailHash(hash, id),
        };
    }

    public get market() {
        return {
            groups: {
                list: () => this.api.getMarketsGroups(),
            },
            group: (id: number) => ({
                fetch: () => this.api.getMarketsGroupsMarketGroupId(id),
            }),
            prices: () => this.api.getMarketsPrices(),
        };
    }
}
